name: Build and Verify
on:
  push:
    branches:
    - main
    paths-ignore:
    - "README.md"
    - "release-notes/*"
  pull_request:
    branches:
    - main
    paths-ignore:
    - "README.md"
    - "release-notes/*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '11', '17']
        os: ['ubuntu-latest']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java_version }}
	cache: 'maven'
        server-id: sonatype-nexus-snapshots
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
    - name: Build
      run: ./mvnw -V -B -ff -ntp verify
